init = "" 
git_status  = "para ver el estado de los archivos"
git_add = "para agregar un archivo al staging area"
git_commit = "para crear punto de control de nuestro código"
git_config_--global_use.email = "para configurar el e-mail del usuario"
git_log = "para ver todos los commits que hemos creado"
git_checkout_-- + nombre "para revertir los cambios de los archivos"
git_diff = "para ver as diferncias en los archivos"